spring.application.name=Data-Persistence-API-Design-Assessment

spring.datasource.url=jdbc:postgresql://localhost:5432/Data_persistence_db
spring.datasource.username=beny_database
spring.datasource.password=mydatabasepassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true